apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-cluster
  namespace: redis
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
    - host: mungtage.site
      http:
        paths:
          - path: /0
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-lb
                port:
                  number: 6379
          - path: /1
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-lb
                port:
                  number: 6379
          - path: /2
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-lb
                port:
                  number: 6379
          - path: /3
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-lb
                port:
                  number: 6379
          - path: /4
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-lb
                port:
                  number: 6379
          - path: /5
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-lb
                port:
                  number: 6379
