apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-cluster
  namespace: redis
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
    - host: mungtage.site
      http:
        paths:
          - path: /0
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-0
                port:
                  number: 6379
                # host: redis-cluster-0.10.0.0.1
          - path: /1
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-1
                port:
                  number: 6379
                # host: redis-cluster-1.10.0.0.1
          - path: /2
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-2
                port:
                  number: 6379
                # host: redis-cluster-2.10.0.0.1
          - path: /3
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-3
                port:
                  number: 6379
                # host: redis-cluster-3.10.0.0.1
          - path: /4
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-4
                port:
                  number: 6379
                # host: redis-cluster-4.10.0.0.1
          - path: /5
            pathType: Prefix
            backend:
              service:
                name: redis-cluster-5
                port:
                  number: 6379
                # host: redis-cluster-5.10.0.0.1
