apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: redis-cluster
  namespace: redis
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.rule: "Host(`mydomain.com`) && PathPrefix(`/redis`)"
spec:
  rules:
    - host: mydomain.com
      http:
        paths:
          - path: /redis
            backend:
              serviceName: redis
              servicePort: 6379
