apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: redis-cluster
  namespace: redis
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
    - host: 3.36.127.101
      http:
        paths:
          - path: /0
            backend:
              serviceName: redis-cluster-0
              servicePort: 6973
          - path: /1
            backend:
              serviceName: redis-cluster-0
              servicePort: 6973
          - path: /2
            backend:
              serviceName: redis-cluster-0
              servicePort: 6973
          - path: /3
            backend:
              serviceName: redis-cluster-0
              servicePort: 6973
          - path: /4
            backend:
              serviceName: redis-cluster-0
              servicePort: 6973
          - path: /5
            backend:
              serviceName: redis-cluster-0
              servicePort: 6973
