apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster
  namespace: redis
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: redis-cluster
          image: redis
          command: ["/bin/sh", "-c"]
          args:
            - kubectl exec -it redis-cluster-0 -n redis -- redis-cli -a educere --cluster create --cluster-replicas 1 $(kubectl get pods -l app=redis-cluster -n redis -o jsonpath='{range.items[*]}{.status.podIP}:6379 {end}')
  backoffLimit: 4
